export const ADD_PROGRAM = 'ADD_PROGRAM';
export const ASSIGN_WORKOUTS_TO_PROGRAM = 'ASSIGN_WORKOUTS_TO_PROGRAM';
export const ADD_WORKOUT = 'ADD_WORKOUT';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const ASSIGN_PROGRESSION_TO_EXERCISE = 'ASSIGN_PROGRESSION_TO_EXERCISE';
export const ASSIGN_EXERCISES_TO_WORKOUT = 'ASSIGN_EXERCISES_TO_WORKOUT';
export const REORDER = 'REORDER';